[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PyBuilder-Generate"
version = "1.0.0"
description = "跨平台 Python 编译脚本生成器 TUI 版本"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "nuitka>=2.8.10",
    "pyfiglet>=1.0.4",
    "pyinstaller>=6.18.0",
    "pyyaml>=6.0.3",
    "textual>=8.0.2",
]

[project.scripts]
pybuilder-tui = "src.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]
